# Generated by Django 5.1.2 on 2024-11-22 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('edificio', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='disponibilidad',
            old_name='fecha',
            new_name='dia',
        ),
        migrations.RenameField(
            model_name='disponibilidad',
            old_name='lugar',
            new_name='direccion',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='detalles',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='horas_disponibles',
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='hora_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='disponibilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.disponibilidad'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='ciudad',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_pacientes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='citas.paciente')),
            ],
        ),
    ]
