# Generated by Django 5.1.2 on 2024-11-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_paciente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
